library(dplyr)
library(ggplot2)
library(ade4)
library(factoextra)
#install.packages("lattice")
#install.packages("geojsonsf")
#install.packages("sf")
#install.packages("readxl")
install.packages("xlsx")
library(xlsx)

library(geojsonsf)
library(sf)
library(lattice)
library(GGally)
library(readxl)
setwd("D:/dem/grid_analysis")
conso_elec<- read.csv("./data/consommation_annuelle_residentielle_adresse_paris.csv",sep=";")
prod_elec<- read.csv("./data/production-electrique-par-filiere-a-la-maille-region.csv", sep=";")
iris_paris<-st_read(dsn="data",layer="iris_paris")
plot(iris_paris)
