library(dplyr)
library(ggplot2)
library(ade4)
library(factoextra)
#install.packages("lattice")
#install.packages("geojsonsf")
#install.packages("sf")
#install.packages("readxl")
install.packages("xlsx")
library(xlsx)

library(geojsonsf)
library(sf)
library(lattice)
library(GGally)
library(readxl)
setwd("D:/dem/grid_analysis")
conso_elec<- read.csv("./data/consommation_annuelle_residentielle_adresse_paris.csv",sep=";")
prod_elec<- read.csv("./data/production-electrique-par-filiere-a-la-maille-region.csv", sep=";")
iris_paris<-st_read(dsn="data",layer="iris_paris")
#plot(iris_paris)
iris_paris_joined_conso<-merge(iris_paris,conso_elec,by.x="CODE_IRIS",by.y="Code.IRIS",type="full")
#plot(iris_paris_joined_conso$geometry)
iris_paris_joined_conso2018<-filter(iris_paris_joined_conso,Année=="2018")
iris_paris_joined_conso2019<-filter(iris_paris_joined_conso,Année=="2019")
iris_paris_joined_conso2020<-filter(iris_paris_joined_conso,Année=="2020")
ggplot(iris_paris_joined_conso2018,aes(x = geometry,y=Consommation.annuelle.moyenne.par.logement.de.l.adresse..MWh.))+geom_tile()
