library(dplyr)
library(ggplot2)
library(ade4)
library(factoextra)
#install.packages("lattice")
#install.packages("geojsonsf")
#install.packages("sf")
#install.packages("readxl")
library(geojsonsf)
library(sf)
library(lattice)
library(GGally)
library("readxl")

conso_elec<- read_excel("D:/dem/grid_analysis/data/production-electrique-par-filiere-a-la-maille-region.xls")
